config/routes.rb
Rails.application.routes.draw do
  root 'logs#index'
  get 'sessions/new'
  get 'users/new'	
  
  get     '/users',   to: 'users#index'
  get     '/logs',    to: 'logs#index'
  get 		'/signup', 	to: 'users#new'
  get 		'/login', 	to: 'sessions#new'
  post 		'/login', 	to: 'sessions#create'
  delete	'/logout', 	to: 'sessions#destroy'

  resources :projects
  resources :logs
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/log.rb
class Log < ApplicationRecord
	attr_accessor :sdate, :edate

	belongs_to :user
	belongs_to :project
	default_scope -> { order(created_at: :desc) }
	validates :user_id, presence: true
	validates :duration, presence: true,  numericality: { only_integer: true, greater_than_or_equal_to: 0}
	validates :remarks, presence: true
	validates :date, presence: true

	def Log.get_total_hours(logs)
    	logs.inject(0) { |sum, l| sum + l.duration }
	end

	def Log.filter_dates(current_user, startdate, enddate)
		current_user.logs.where("date >= ? AND date <= ?", startdate, enddate)
	end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :edit, :update, :destroy]
  before_action :correct_user, only: :destroy
  before_action :prepare_projects

  # GET /logs
  # GET /logs.json
  def index
    @logs = current_user.logs

    if params[:start_date].present? && params[:end_date].present?
      date_filters(params[:start_date], params[:end_date])
      if params[:start_date] <= params[:end_date]
        @logs = Log.filter_dates(current_user, params[:start_date], params[:end_date])
      else
        date_filters(nil,nil)
        flash_alerts("End date cannot be earlier than start date.", root_path)
      end
    end
    @total_hours = Log.get_total_hours(@logs)
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
    @log = Log.find(params[:id])
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = current_user.logs.build(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to logs_path, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:duration, :project_id, :remarks, :date, :user_id, :start_date, :end_date)
    end

    def correct_user
      @log = current_user.logs.find_by(id: params[:id])
      redirect_to login_path if @log.nil?
    end

    def prepare_projects
      @projects = Project.all
    end

    def date_filters(startdate, enddate)
      # Variables for printing on views
      @start_date = startdate
      @end_date = enddate
    end

    def flash_alerts(alert, path)
      flash.now[:notice] = alert
      return path
    end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_with(model: log, local: true) do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration, id: :log_duration %>
  </div>

  <div class="field">
    <%= form.label :project %><br />
    <%= form.collection_select(:project_id, @projects, :id, :name, :include_blank => "Please select Projects") %>
  </div>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_field :remarks, id: :log_remarks %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date, id: :log_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logs/_log.html.erb
<li id="log-<%= log.id %>">
  <span class="duration"><%= log.duration %></span>
  <span class="project"><%= log.project.name %></span>
  <span class="remarks"><%= log.remarks %></span>
  <span class="date"><%= log.date %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(log.created_at) %> ago.
  </span>
</li>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logs</h1>

<h3><%= link_to 'Create New Log', new_log_path, class: "btn btn-primary" %></h3>

<br>
<div>
  <%= form_tag(logs_path, method: :get) do %>
  Select date: 
    <%= date_field_tag :start_date, @start_date, required: true %>
    -
    <%= date_field_tag :end_date, @end_date, required: true %>
    <%= submit_tag 'Filter', class: "btn btn-filters btn-filter" %>
    <%= link_to 'Reset', logs_path, class: "btn btn-filters btn-reset" %>
  <% end %>
</div>
<br>
<div>
  <h4><%=@start_date%> - <%=@end_date%></h4>
  <h3>TOTAL: <%= @total_hours %> hours</h3>
</div>
<div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Duration</th>
        <th>Project</th>
        <th>Remarks</th>
        <th>Date</th>
        <th>Actions</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @logs.each do |log| %>
        <tr>
          <td><%= log.duration %>h</td>
          <td><%= log.project.name %></td>
          <td><%= log.remarks %></td>
          <td><%= log.date.strftime("%b %d, %Y") %></td>
          <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Duration:</strong>
  <%= @log.duration %>hr
</p>

<p>
  <strong>Project:</strong>
  <%= @log.project.name %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @log.remarks %>
</p>

<p>
  <strong>Date:</strong>
  <%= @log.date.strftime("%b %d, %Y") %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>